# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#    tags: 
#      - 'v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    # - uses: egordm/gha-yarn-node-cache@v1
        
      - name: Setup php and conposer
        uses: php-actions/composer@v2 
        
      - name: Setup node for yarn 
        uses: actions/setup-node@v1

      
      - run: npm install -g yarn
        
      - name: setup yarn dependencies
        run: |
         yarn install
           
      - name: webpack front
        run: yarn encore prod 
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package_t
          path: |
            public        
